spring:
  application:
    name: item-service #在注册中心用的名字
    
server:
  port: 8001

#eureka注册配置
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka #注册发现地址